databases:
  - name: postgreszoum
    databaseName: postgreszoum
    user: postgreszoum_user

services:
  - type: web
    name: Budget
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgreszoum
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false